default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: organizador_development
  host: localhost
  user: postgres
  password: contra127

test:
  <<: *default
  database: organizador_test
  host: localhost
  user: postgres
  password: contra127


production:
  <<: *default
  database: organizador_production
  username: organizador
  password: <%= ENV['ORGANIZADOR_DATABASE_PASSWORD'] %>
